@startuml
actor 教师
activate 教师
教师 ->MAJOR_COURSE_TERM:查询开课信息
activate MAJOR_COURSE_TERM
MAJOR_COURSE_TERM->MAJORS:查询专业详细信息
MAJOR_COURSE_TERM->COURSES:查询课程详细信息
MAJOR_COURSE_TERM->TERM:查询学期详细信息
MAJOR_COURSE_TERM-->教师:返回开课相关信息
deactivate MAJOR_COURSE_TERM
教师 ->COURSE_TEACHER:提交并添加课程和教师的关联信息
activate COURSE_TEACHER
COURSE_TEACHER-->教师:返回添加结果
deactivate COURSE_TEACHER
deactivate 教师
actor 学生
activate 学生
学生 ->COURSE_TEACHER:查询已被教师选择的开课关联信息
activate COURSE_TEACHER
COURSE_TEACHER->MAJOR_COURSE_TERM:查询开课信息
activate MAJOR_COURSE_TERM
MAJOR_COURSE_TERM->MAJORS:查询专业详细信息
MAJOR_COURSE_TERM->COURSES:查询课程详细信息
MAJOR_COURSE_TERM->TERM:查询学期详细信息
MAJOR_COURSE_TERM-->COURSE_TEACHER:返回开课信息
deactivate MAJOR_COURSE_TERM
COURSE_TEACHER-->学生:返回开课与教师相关信息
deactivate COURSE_TEACHER
学生 ->COURSE_STUDENTS:提交并添加开课课程、教师与学生的关联信息
activate COURSE_STUDENTS
COURSE_STUDENTS-->学生:返回添加结果
deactivate COURSE_STUDENTS
deactivate 学生
@enduml